language: csharp
solution: testing.sln
install:
 - nuget restore testing.sln
 - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
 - xbuild /p:Configuration=Release testing.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./HomeExercises/bin/Release/ObjectComparison.dll
